### ISSUE TITLE
'no such file or directory' error when using docker image

### ISSUE THREAD

**Issue by lxz81** [EmbarkStudios/wg-ui#128]
**Describe the bug**
When I use the latest docker image, I get the following error:
`standard_init_linux.go:219: exec user process caused: no such file or directory`

**To Reproduce**
1. I added the following to my docker-compose.yml:
```
  wireguard-ui:
    image: embarkstudios/wireguard-ui:latest
    container_name: wireguard-ui
    privileged: true
    network_mode: "host"
    ports:
      - 25444:25444
      - 51820:51820/udp
    volumes:
      - /opt/wireguard-ui:/data
    environment:
      - PGID=1000
      - PUID=1000
      - WIREGUARD_UI_LISTEN_ADDRESS=:25444
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_WG_ENDPOINT=vpn.somehost.com:51820
      - WIREGUARD_UI_CLIENT_IP_RANGE=10.8.0.1/24
      - WIREGUARD_UI_WG_DNS=94.140.14.14
 #     - WIREGUARD_UI_NAT=true
 #     - WIREGUARD_UI_NAT_DEVICE=eno1
    restart: always

```
2. run docker-compose up wireguard-ui

**Expected behavior**
wg-ui to be running

**Actual behavior**
The following error:
standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by kanenses** [comment]
same issue here

**Comment by Ixbitz** [comment]
Same issue here when trying to run the command provided in the README:

OS: Ubuntu 20.04.2 LTS "Focal"
Docker version: 20.10.6, build 370c289


Error message: `standard_init_linux.go:228: exec user process caused: no such file or directory`

**Comment by enriquecaballero** [comment]
Same. On Alpine.

```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

**Comment by enriquecaballero** [comment]
Turns out, Alpine doesn't have any of the libc6 binaries required to run the go wg-ui binary. This should probably be added to the official Dockerfile's in this repository. But a quick fix would be to create a Dockerfile with:
```
FROM embarkstudios/wireguard-ui

RUN apk add --no-cache libc6-compat
```

And then use tell your docker-compose to build the image off that Dockerfile:
```
version: "3"
services:
  wireguard-ui:
    build:
      context: .
    restart: always
    privileged: true
    network_mode: host
    environment:
      - CGO_ENABLED=0
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_WG_ENDPOINT=vpn.mydomain.com:51820
      - WIREGUARD_UI_WG_DNS=10.0.0.1
      - WIREGUARD_UI_CLIENT_IP_RANGE=10.10.0.1/24
      - WIREGUARD_UI_NAT_DEVICE=eth0
      - WIREGUARD_UI_LISTEN_ADDRESS=:8080
    volumes:
      - /opt/wireguard-ui:/data
```

Worked for me.
