### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by fniko** [EmbarkStudios/wg-ui#37]
**Describe the bug**
I am unable to run this image in Kubernetes, the pod keeps failing with `CrashLoopBackOff` and the logs says `level=fatal msg="operation not supported"` only. Do you have any advice about how to troubleshoot this?

**To Reproduce**
1. Create deployment.yml
2. `kubectl apply -f deployment.yml`

**Expected behavior**
The pod should start

**Code**
[Describe pod ](https://pastebin.com/d8bhftDU)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wireguard
  template:
    metadata:
      labels:
        component: wireguard
    spec:
      volumes:
        - name: wg-data
          persistentVolumeClaim:
            claimName: wg-pv-claim
      containers:
        - name: wg-ui
          image: "embarkstudios/wireguard-ui"
          command: ["/wireguard-ui"]
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: gui
            - containerPort: 5555
              name: wireguard
          volumeMounts:
            - mountPath: /data
              name: wg-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  labels:
    component: wireguard
spec:
  ports:
    - name: gui
      port: 8080
      targetPort: 8080
    - name: wireguard
      port: 5555
      targetPort: 5555
  selector:
    component: wireguard
  type: LoadBalancer
```

Do you have any tips how to run in k8s or debug?
